import React from "react";
import "../../styles/section/_skillsnprojects.scss";

const SkillsnProjects = () => {
    return(
        <section className="skillsnproject" >
            <div className="container">
                <div className="text-running">
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                    <h1>~Let's Know Me More~</h1>
                </div>
            </div>
        </section>
    );
};

export default SkillsnProjects;